// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (email, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, email, role, created_at, updated_at
`

type CreateAdminUserParams struct {
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         AdminRole `json:"role"`
}

type CreateAdminUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Role      AdminRole          `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (CreateAdminUserRow, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.Email, arg.PasswordHash, arg.Role)
	var i CreateAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAdminUser = `-- name: DeleteAdminUser :exec
DELETE FROM admin_users WHERE id = $1
`

func (q *Queries) DeleteAdminUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdminUser, id)
	return err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, email, role, created_at, updated_at
FROM admin_users
ORDER BY created_at ASC
`

type ListAdminUsersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Role      AdminRole          `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminUsersRow
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
