// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bulk.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateReviewStatus = `-- name: BulkUpdateReviewStatus :execrows
UPDATE reviews
SET status = $1, updated_at = now()
WHERE id = ANY($2::uuid[])
`

type BulkUpdateReviewStatusParams struct {
	Status ReviewStatus  `json:"status"`
	Ids    []pgtype.UUID `json:"ids"`
}

func (q *Queries) BulkUpdateReviewStatus(ctx context.Context, arg BulkUpdateReviewStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUpdateReviewStatus, arg.Status, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
