// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminRole string

const (
	AdminRoleSuperadmin AdminRole = "superadmin"
	AdminRoleAdmin      AdminRole = "admin"
	AdminRoleModerator  AdminRole = "moderator"
)

func (e *AdminRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminRole(s)
	case string:
		*e = AdminRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminRole: %T", src)
	}
	return nil
}

type NullAdminRole struct {
	AdminRole AdminRole `json:"admin_role"`
	Valid     bool      `json:"valid"` // Valid is true if AdminRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminRole) Scan(value interface{}) error {
	if value == nil {
		ns.AdminRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminRole), nil
}

func (e AdminRole) Valid() bool {
	switch e {
	case AdminRoleSuperadmin,
		AdminRoleAdmin,
		AdminRoleModerator:
		return true
	}
	return false
}

func AllAdminRoleValues() []AdminRole {
	return []AdminRole{
		AdminRoleSuperadmin,
		AdminRoleAdmin,
		AdminRoleModerator,
	}
}

type ReviewStatus string

const (
	ReviewStatusPending  ReviewStatus = "pending"
	ReviewStatusApproved ReviewStatus = "approved"
	ReviewStatusRejected ReviewStatus = "rejected"
	ReviewStatusFlagged  ReviewStatus = "flagged"
)

func (e *ReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatus(s)
	case string:
		*e = ReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatus: %T", src)
	}
	return nil
}

type NullReviewStatus struct {
	ReviewStatus ReviewStatus `json:"review_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatus), nil
}

func (e ReviewStatus) Valid() bool {
	switch e {
	case ReviewStatusPending,
		ReviewStatusApproved,
		ReviewStatusRejected,
		ReviewStatusFlagged:
		return true
	}
	return false
}

func AllReviewStatusValues() []ReviewStatus {
	return []ReviewStatus{
		ReviewStatusPending,
		ReviewStatusApproved,
		ReviewStatusRejected,
		ReviewStatusFlagged,
	}
}

type AdminUser struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         AdminRole          `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ExternalID string             `json:"external_id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Review struct {
	ID               pgtype.UUID        `json:"id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	AuthorName       string             `json:"author_name"`
	AuthorEmail      *string            `json:"author_email"`
	Rating           int16              `json:"rating"`
	Title            *string            `json:"title"`
	Body             string             `json:"body"`
	Status           ReviewStatus       `json:"status"`
	VerifiedPurchase bool               `json:"verified_purchase"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	UserAgent        *string            `json:"user_agent"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	ApiKey    string             `json:"api_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
