// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (tenant_id, external_id, name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, external_id, name, created_at
`

type CreateProductParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ExternalID string      `json:"external_id"`
	Name       string      `json:"name"`
}

type CreateProductRow struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ExternalID string             `json:"external_id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.TenantID, arg.ExternalID, arg.Name)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT p.id, p.tenant_id, p.external_id, p.name, p.created_at, t.name AS tenant_name
FROM products p
JOIN tenants t ON t.id = p.tenant_id
WHERE p.id = $1
`

type GetProductRow struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ExternalID string             `json:"external_id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TenantName string             `json:"tenant_name"`
}

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
		&i.TenantName,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.tenant_id, p.external_id, p.name, p.created_at, t.name AS tenant_name
FROM products p
JOIN tenants t ON t.id = p.tenant_id
WHERE ($1::uuid IS NULL OR p.tenant_id = $1)
ORDER BY p.created_at DESC
`

type ListProductsRow struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ExternalID string             `json:"external_id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TenantName string             `json:"tenant_name"`
}

func (q *Queries) ListProducts(ctx context.Context, tenantID pgtype.UUID) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalID,
			&i.Name,
			&i.CreatedAt,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductName = `-- name: UpdateProductName :one
UPDATE products SET name = $1, updated_at = now()
WHERE id = $2
RETURNING id, tenant_id, external_id, name, created_at
`

type UpdateProductNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

type UpdateProductNameRow struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ExternalID string             `json:"external_id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateProductName(ctx context.Context, arg UpdateProductNameParams) (UpdateProductNameRow, error) {
	row := q.db.QueryRow(ctx, updateProductName, arg.Name, arg.ID)
	var i UpdateProductNameRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
