// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: public.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApprovedReviews = `-- name: CountApprovedReviews :one
SELECT COUNT(*), COALESCE(AVG(rating), 0)::FLOAT8 AS avg_rating
FROM reviews
WHERE product_id = $1 AND status = 'approved'
`

type CountApprovedReviewsRow struct {
	Count     int64   `json:"count"`
	AvgRating float64 `json:"avg_rating"`
}

func (q *Queries) CountApprovedReviews(ctx context.Context, productID pgtype.UUID) (CountApprovedReviewsRow, error) {
	row := q.db.QueryRow(ctx, countApprovedReviews, productID)
	var i CountApprovedReviewsRow
	err := row.Scan(&i.Count, &i.AvgRating)
	return i, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
    product_id, tenant_id, author_name, author_email,
    rating, title, body, ip_address, user_agent, verified_purchase
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, product_id, tenant_id, author_name, author_email, rating, title, body, status, verified_purchase, ip_address, user_agent, created_at, updated_at
`

type CreateReviewParams struct {
	ProductID        pgtype.UUID `json:"product_id"`
	TenantID         pgtype.UUID `json:"tenant_id"`
	AuthorName       string      `json:"author_name"`
	AuthorEmail      *string     `json:"author_email"`
	Rating           int16       `json:"rating"`
	Title            *string     `json:"title"`
	Body             string      `json:"body"`
	IpAddress        *netip.Addr `json:"ip_address"`
	UserAgent        *string     `json:"user_agent"`
	VerifiedPurchase bool        `json:"verified_purchase"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ProductID,
		arg.TenantID,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.Rating,
		arg.Title,
		arg.Body,
		arg.IpAddress,
		arg.UserAgent,
		arg.VerifiedPurchase,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.TenantID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.VerifiedPurchase,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByExternalID = `-- name: GetProductByExternalID :one
SELECT id FROM products WHERE tenant_id = $1 AND external_id = $2
`

type GetProductByExternalIDParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ExternalID string      `json:"external_id"`
}

func (q *Queries) GetProductByExternalID(ctx context.Context, arg GetProductByExternalIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getProductByExternalID, arg.TenantID, arg.ExternalID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getTenantByAPIKey = `-- name: GetTenantByAPIKey :one
SELECT id, name FROM tenants WHERE api_key = $1
`

type GetTenantByAPIKeyRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) GetTenantByAPIKey(ctx context.Context, apiKey string) (GetTenantByAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getTenantByAPIKey, apiKey)
	var i GetTenantByAPIKeyRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listApprovedReviews = `-- name: ListApprovedReviews :many
SELECT
    id, author_name, rating, title, body, verified_purchase, created_at
FROM reviews
WHERE product_id = $1 AND status = 'approved'
ORDER BY created_at DESC
LIMIT  $3
OFFSET $2
`

type ListApprovedReviewsParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
}

type ListApprovedReviewsRow struct {
	ID               pgtype.UUID        `json:"id"`
	AuthorName       string             `json:"author_name"`
	Rating           int16              `json:"rating"`
	Title            *string            `json:"title"`
	Body             string             `json:"body"`
	VerifiedPurchase bool               `json:"verified_purchase"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListApprovedReviews(ctx context.Context, arg ListApprovedReviewsParams) ([]ListApprovedReviewsRow, error) {
	rows, err := q.db.Query(ctx, listApprovedReviews, arg.ProductID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovedReviewsRow
	for rows.Next() {
		var i ListApprovedReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorName,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.VerifiedPurchase,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
