// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReviews = `-- name: CountReviews :one
SELECT COUNT(*) FROM reviews
WHERE
    ($1::review_status IS NULL OR status = $1)
    AND ($2::uuid IS NULL OR tenant_id = $2)
`

type CountReviewsParams struct {
	Status   NullReviewStatus `json:"status"`
	TenantID pgtype.UUID      `json:"tenant_id"`
}

func (q *Queries) CountReviews(ctx context.Context, arg CountReviewsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReviews, arg.Status, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReview = `-- name: GetReview :one
SELECT
    r.id,
    r.product_id,
    r.tenant_id,
    r.author_name,
    r.author_email,
    r.rating,
    r.title,
    r.body,
    r.status,
    r.verified_purchase,
    r.ip_address,
    r.user_agent,
    r.created_at,
    r.updated_at,
    p.name AS product_name,
    t.name AS tenant_name
FROM reviews r
JOIN products p ON p.id = r.product_id
JOIN tenants t  ON t.id = r.tenant_id
WHERE r.id = $1
`

type GetReviewRow struct {
	ID               pgtype.UUID        `json:"id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	AuthorName       string             `json:"author_name"`
	AuthorEmail      *string            `json:"author_email"`
	Rating           int16              `json:"rating"`
	Title            *string            `json:"title"`
	Body             string             `json:"body"`
	Status           ReviewStatus       `json:"status"`
	VerifiedPurchase bool               `json:"verified_purchase"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	UserAgent        *string            `json:"user_agent"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ProductName      string             `json:"product_name"`
	TenantName       string             `json:"tenant_name"`
}

func (q *Queries) GetReview(ctx context.Context, id pgtype.UUID) (GetReviewRow, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i GetReviewRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.TenantID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.VerifiedPurchase,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductName,
		&i.TenantName,
	)
	return i, err
}

const listReviews = `-- name: ListReviews :many
SELECT
    r.id,
    r.product_id,
    r.tenant_id,
    r.author_name,
    r.author_email,
    r.rating,
    r.title,
    r.body,
    r.status,
    r.verified_purchase,
    r.ip_address,
    r.user_agent,
    r.created_at,
    r.updated_at,
    p.name AS product_name,
    t.name AS tenant_name
FROM reviews r
JOIN products p ON p.id = r.product_id
JOIN tenants t  ON t.id = r.tenant_id
WHERE
    ($1::review_status IS NULL OR r.status = $1)
    AND ($2::uuid IS NULL OR r.tenant_id = $2)
ORDER BY r.created_at DESC
LIMIT  $4
OFFSET $3
`

type ListReviewsParams struct {
	Status   NullReviewStatus `json:"status"`
	TenantID pgtype.UUID      `json:"tenant_id"`
	Offset   int32            `json:"offset"`
	Limit    int32            `json:"limit"`
}

type ListReviewsRow struct {
	ID               pgtype.UUID        `json:"id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	AuthorName       string             `json:"author_name"`
	AuthorEmail      *string            `json:"author_email"`
	Rating           int16              `json:"rating"`
	Title            *string            `json:"title"`
	Body             string             `json:"body"`
	Status           ReviewStatus       `json:"status"`
	VerifiedPurchase bool               `json:"verified_purchase"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	UserAgent        *string            `json:"user_agent"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ProductName      string             `json:"product_name"`
	TenantName       string             `json:"tenant_name"`
}

func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]ListReviewsRow, error) {
	rows, err := q.db.Query(ctx, listReviews,
		arg.Status,
		arg.TenantID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsRow
	for rows.Next() {
		var i ListReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.TenantID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.VerifiedPurchase,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReviewStatus = `-- name: UpdateReviewStatus :one
UPDATE reviews
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, product_id, tenant_id, author_name, author_email, rating, title, body, status, verified_purchase, ip_address, user_agent, created_at, updated_at
`

type UpdateReviewStatusParams struct {
	ID     pgtype.UUID  `json:"id"`
	Status ReviewStatus `json:"status"`
}

func (q *Queries) UpdateReviewStatus(ctx context.Context, arg UpdateReviewStatusParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReviewStatus, arg.ID, arg.Status)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.TenantID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.VerifiedPurchase,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
