// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package repository

import (
	"context"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    COUNT(*) FILTER (WHERE status = 'pending')  AS pending,
    COUNT(*) FILTER (WHERE status = 'approved') AS approved,
    COUNT(*) FILTER (WHERE status = 'rejected') AS rejected,
    COUNT(*) FILTER (WHERE status = 'flagged')  AS flagged,
    COUNT(*)                                     AS total
FROM reviews
`

type GetDashboardStatsRow struct {
	Pending  int64 `json:"pending"`
	Approved int64 `json:"approved"`
	Rejected int64 `json:"rejected"`
	Flagged  int64 `json:"flagged"`
	Total    int64 `json:"total"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.Pending,
		&i.Approved,
		&i.Rejected,
		&i.Flagged,
		&i.Total,
	)
	return i, err
}

const reviewTrends = `-- name: ReviewTrends :many
SELECT
    TO_CHAR(DATE(created_at AT TIME ZONE 'UTC'), 'YYYY-MM-DD') AS day,
    COUNT(*)::int AS count
FROM reviews
WHERE created_at >= NOW() - INTERVAL '30 days'
GROUP BY day
ORDER BY day ASC
`

type ReviewTrendsRow struct {
	Day   string `json:"day"`
	Count int32  `json:"count"`
}

func (q *Queries) ReviewTrends(ctx context.Context) ([]ReviewTrendsRow, error) {
	rows, err := q.db.Query(ctx, reviewTrends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewTrendsRow
	for rows.Next() {
		var i ReviewTrendsRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
