// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package repository

import (
	"context"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    COUNT(*) FILTER (WHERE status = 'pending')  AS pending,
    COUNT(*) FILTER (WHERE status = 'approved') AS approved,
    COUNT(*) FILTER (WHERE status = 'rejected') AS rejected,
    COUNT(*) FILTER (WHERE status = 'flagged')  AS flagged,
    COUNT(*)                                     AS total
FROM reviews
`

type GetDashboardStatsRow struct {
	Pending  int64 `json:"pending"`
	Approved int64 `json:"approved"`
	Rejected int64 `json:"rejected"`
	Flagged  int64 `json:"flagged"`
	Total    int64 `json:"total"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.Pending,
		&i.Approved,
		&i.Rejected,
		&i.Flagged,
		&i.Total,
	)
	return i, err
}
