// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name) VALUES ($1) RETURNING id, name, api_key, created_at
`

type CreateTenantRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	ApiKey    string             `json:"api_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTenant(ctx context.Context, name string) (CreateTenantRow, error) {
	row := q.db.QueryRow(ctx, createTenant, name)
	var i CreateTenantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, api_key, created_at FROM tenants WHERE id = $1
`

type GetTenantRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	ApiKey    string             `json:"api_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (GetTenantRow, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i GetTenantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, api_key, created_at FROM tenants ORDER BY created_at DESC
`

type ListTenantsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	ApiKey    string             `json:"api_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTenants(ctx context.Context) ([]ListTenantsRow, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantsRow
	for rows.Next() {
		var i ListTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateTenantAPIKey = `-- name: RotateTenantAPIKey :one
UPDATE tenants SET api_key = gen_random_uuid()::text, updated_at = now()
WHERE id = $1
RETURNING id, name, api_key, created_at
`

type RotateTenantAPIKeyRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	ApiKey    string             `json:"api_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) RotateTenantAPIKey(ctx context.Context, id pgtype.UUID) (RotateTenantAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, rotateTenantAPIKey, id)
	var i RotateTenantAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}

const updateTenantName = `-- name: UpdateTenantName :one
UPDATE tenants SET name = $1, updated_at = now()
WHERE id = $2
RETURNING id, name, api_key, created_at
`

type UpdateTenantNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

type UpdateTenantNameRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	ApiKey    string             `json:"api_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateTenantName(ctx context.Context, arg UpdateTenantNameParams) (UpdateTenantNameRow, error) {
	row := q.db.QueryRow(ctx, updateTenantName, arg.Name, arg.ID)
	var i UpdateTenantNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}
